export const acceptCases = [
  { accept: "", markdown: false },
  { accept: "*/*", markdown: false },
  { accept: "text/*", markdown: false },
  { accept: "TEXT/MARKDOWN", markdown: true },
  { accept: "text/markdown ; q=0.9", markdown: true },
  { accept: "text/markdown\t; q=0.9, text/html ; q=1", markdown: false },
  { accept: "text/markdown ; q=1, text/html\t; q=0.9", markdown: true },
  { accept: "text/markdown ; q=0, text/html ; q=0.9", markdown: false },
  { accept: "text/markdown;q=0.5,text/*;q=1", markdown: false },
  { accept: "text/markdown;q=0.5,*/*;q=1", markdown: false },
  { accept: "text/markdown;q=0.5,text/*;q=0.2,*/*;q=1", markdown: true },
  { accept: "text/markdown;q=0,text/*;q=1", markdown: false },
  { accept: "text/html;q=0,text/*;q=1", markdown: true },
  { accept: "text/html;q=0.8,text/*;q=0.9", markdown: true },
  { accept: "text/markdown,text/html", markdown: true },
  { accept: "text/markdown;q=wrong", markdown: false },
  { accept: "text/markdown;q=2", markdown: false },
  { accept: "text/markdown;q=1e0", markdown: false },
  { accept: "text/markdown;q=0.9999", markdown: false },
];
