import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { test } from "@playwright/test";

const execFileAsync = promisify(execFile);
const root = fileURLToPath(new URL("../", import.meta.url));

async function checkFonts(source: string) {
  await execFileAsync(
    process.execPath,
    [
      "--unhandled-rejections=strict",
      "--import",
      "tsx",
      "--input-type=module",
      "--eval",
      `
        import assert from "node:assert/strict";
        const { default: og, loadFonts } = await import("./api/og.ts");
        ${source}
      `,
    ],
    {
      cwd: root,
      env: { ...process.env, OG_IMAGE_SECRET: "isolated-og-font-test-key" },
    },
  );
}

test("OG fonts reuse the same reads for concurrent and later warm requests", async () => {
  await checkFonts(`
    const urls = [];
    let bodyReads = 0;
    globalThis.fetch = async (url) => {
      urls.push(url);
      const bytes = new Uint8Array([urls.length]).buffer;
      return { ok: true, arrayBuffer: async () => { bodyReads++; return bytes; } };
    };

    const first = loadFonts();
    const concurrent = loadFonts();
    assert.equal(concurrent, first);
    const fonts = await first;
    assert.equal(await concurrent, fonts);
    assert.equal(loadFonts(), first);
    assert.equal(await loadFonts(), fonts);
    assert.equal(urls.length, 2);
    assert.equal(bodyReads, 2);
    assert.deepEqual(fonts.map((data) => [...new Uint8Array(data)]), [[1], [2]]);
    assert.ok(urls.every((url) => url instanceof URL));
    assert.ok(urls[0].pathname.endsWith("/assets/og/Inter-Regular.ttf"));
    assert.ok(urls[1].pathname.endsWith("/assets/og/Inter-Black.ttf"));
  `);
});

test("OG fonts observe both simultaneous failures without an unhandled rejection", async () => {
  await checkFonts(`
    const unhandled = [];
    process.on("unhandledRejection", (error) => unhandled.push(error));
    const rejects = [];
    globalThis.fetch = () => new Promise((resolve, reject) => rejects.push(reject));

    const regularFailure = new Error("regular font unavailable");
    const blackFailure = new Error("black font unavailable");
    const result = loadFonts().catch((error) => error);
    assert.equal(rejects.length, 2);
    rejects[0](regularFailure);
    rejects[1](blackFailure);
    assert.equal(await result, regularFailure);
    await new Promise(setImmediate);
    assert.deepEqual(unhandled, []);
  `);
});

test("OG fonts retry after failure and cache the successful retry", async () => {
  await checkFonts(`
    let fetches = 0;
    let bodyReads = 0;
    globalThis.fetch = async () => {
      fetches++;
      return { ok: true, arrayBuffer: async () => {
        bodyReads++;
        throw new Error("font body unavailable");
      } };
    };
    const failed = loadFonts();
    await assert.rejects(failed, /font body unavailable/);
    assert.equal(fetches, 2);
    assert.equal(bodyReads, 2);

    const bytes = new Uint8Array([42]).buffer;
    globalThis.fetch = async () => {
      fetches++;
      return { ok: true, arrayBuffer: async () => { bodyReads++; return bytes; } };
    };
    const retry = loadFonts();
    assert.notEqual(retry, failed);
    assert.equal(loadFonts(), retry);
    assert.deepEqual(await retry, [bytes, bytes]);
    assert.equal(loadFonts(), retry);
    await loadFonts();
    assert.equal(fetches, 4);
    assert.equal(bodyReads, 4);
  `);
});

test("OG font HTTP failures reject and allow a later retry", async () => {
  await checkFonts(`
    let fetches = 0;
    globalThis.fetch = async () => { fetches++; return new Response("offline", { status: 503 }); };
    await assert.rejects(loadFonts(), /HTTP 503/);
    assert.equal(fetches, 2);
    globalThis.fetch = async () => { fetches++; return new Response(new Uint8Array([42])); };
    const result = await loadFonts();
    assert.deepEqual(result.map(bytes => [...new Uint8Array(bytes)]), [[42], [42]]);
    assert.equal(fetches, 4);
  `);
});

test("unauthorized OG requests never start font I/O", async () => {
  await checkFonts(`
    let fetches = 0;
    globalThis.fetch = async () => {
      fetches++;
      throw new Error("unexpected font I/O");
    };
    console.error = () => {};
    const post = "1700000000000\\t3\\tSynthetic test post\\t";
    for (const token of ["", "invalid-token"]) {
      const url = new URL("https://example.invalid/api/og");
      url.searchParams.set("post", post);
      url.searchParams.set("token", token);
      const response = await og(new Request(url));
      assert.equal(response.status, 401);
      assert.deepEqual(await response.json(), {
        error: {
          code: "INVALID_TOKEN",
          message: "Invalid token.",
          hint: "Use the image URL generated by the site without changing post or token.",
        },
      });
    }
    assert.equal(fetches, 0);
  `);
});
